spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://192.168.154.93:9411
  sleuth:
      sampler:
        probability: 1 #采样率 1为全部采集
#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: my_tx_group
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
