server:
  port: 80

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启注册中心路由功能
          lower-case-service-id: true
      routes:
        - id: payment_routh
#          uri: http://localhost:9001
          uri: lb://nacos-payment-provider #此处如果有问题，请注意依赖spring-cloud-starter-netflix-eureka-client依赖不能错
          predicates:
            - Path=/payment/nacos/**
        - id: payment_routh2
#          uri: http://localhost:9001
          uri: lb://nacos-payment-provider
          predicates:
            - Path=/payment/config/info

        - id: order_routh1
#          uri: http://localhost:9001
          uri: lb://nacos-order-consumer
          predicates:
            - Path=/consumer/payment/config/info

        - id: order_routh2
        #          uri: http://localhost:9001
          uri: lb://nacos-order-consumer
          predicates:
            - Path=/consumer/**
    nacos:
      discovery:
        server-addr: 192.168.154.93:8848,192.168.154.93:8849,192.168.154.93:8850
        #namespace: 91f262e7-a1ba-4b36-90ad-c0f37519c261 #dev
        namespace: 8551d28d-04a5-4c16-a53e-8496a97ab41c #test
        register-enabled: true