apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-storage
  name: cloud-storage
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 9010
    nodePort: 9010
  selector:
    app: cloud-storage
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-storage-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: cloud-storage
  template:
    metadata:
      labels:
        app: cloud-storage
    spec:
      containers:
      - name: cloud-storage
        image: cloud-storage:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9010