apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-payment
  name: cloud-payment
spec:
  ports:
  - port: 9081
    protocol: TCP
    targetPort: 9001
    nodePort: 9001
  selector:
    app: cloud-payment
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-payment-deployment
spec:
  replicas: 3
  selector:
      matchLabels:
        app: cloud-payment
  template:
    metadata:
      labels:
        app: cloud-payment
    spec:
      containers:
      - name: cloud-payment
        image: cloud-pament:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 9001