apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-payment
  name: cloud-payment
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 9001
  selector:
    app: cloud-payment
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-payment-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: cloud-payment
  template:
    metadata:
      labels:
        app: cloud-payment
    spec:
      containers:
      - name: cloud-payment
        image: rain2020/cloud-payment:latest
        ports:
        - containerPort: 9001