FROM docker.io/openjdk:8-jdk
MAINTAINER cloud-payment liuchunlin.com

copy cloudalibaba-payment9001-1.0-SNAPSHOT.jar /cloudalibaba-payment9001-1.0-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/cloudalibaba-payment9001-1.0-SNAPSHOT.jar"]