FROM docker.io/openjdk:8-jdk
MAINTAINvi NER cloud-payment liuchunlin.com

cp cloudalibaba-payment9001-1.0-SNAPSHOT.jar /cloudalibaba-payment9001-1.0-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/cloudalibaba-payment9001-1.0-SNAPSHOT.jar"]