FROM docker.io/openjdk:8-jdk
MAINTAINvi NER cloud-payment liuchunlin.com

cp cloudalibaba-order83-1.0-SNAPSHOT.jar /cloudalibaba-order83-1.0-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/cloudalibaba-order83-1.0-SNAPSHOT.jar"]