FROM docker.io/openjdk:8-jdk
MAINTAINER cloud-order liuchunlin.com

copy cloudalibaba-order83-1.0-SNAPSHOT.jar /cloudalibaba-order83-1.0-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/cloudalibaba-order83-1.0-SNAPSHOT.jar"]