apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-gateway
  name: cloud-gateway
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
    nodePort: 80
  selector:
    app: cloud-gateway
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-deployment
spec:
  replicas: 3
  selector:
      matchLabels:
        app: cloud-gateway
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      containers:
      - name: cloud-gateway
        image: cloud-gateway:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80